[dependencies]

[package]
  cjc-version = "0.55.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "priorityqueue4cj"
  output-type = "dynamic"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "0.0.1"
  package-configuration = {}
